<a href="https://colab.research.google.com/github/Hussein-Ahmad-94/Tasks/blob/Colab/TASK_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### write a function that transform tme series into machine supervised learning using windowing

In [ ]:
def window_transform_series(series, window_size, horizon_size):
    X, y = [], []
    for i in range(len(series) - window_size - horizon_size + 1):
        X.append(series[i:i + window_size])
        y.append(series[i + window_size: i + window_size + horizon_size])
    X,y=np.squeeze(np.array(X)),np.squeeze(np.array(y))
    return X, y


In [ ]:
def window_transform_series_fake(series, window_size):
    X =  []
    for i in range(len(series) - window_size+ 1):
        X.append(series[i:i + window_size])
    X= np.squeeze(np.array(X))
    return X

In [ ]:
import numpy as np

window_size = 4
time_series = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
X = window_transform_series_fake(time_series, window_size)
print(X)

[[ 1  2  3]
 [ 2  3  4]
 [ 3  4  5]
 [ 4  5  6]
 [ 5  6  7]
 [ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]]


In [ ]:
import numpy as np

window_size = 3
horizon_size = 2
time_series = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
X, y = window_transform_series(time_series, window_size, horizon_size)
print(X)
print(y)

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]]
[[ 4  5]
 [ 5  6]
 [ 6  7]
 [ 7  8]
 [ 8  9]
 [ 9 10]]


In [ ]:
import keras
from keras.engine.input_layer import node_module
from keras.models import Sequential
from keras.layers import Dense

def MLP_1 (n_input,n_hidden,n_output,X_train, y_train):


  # Define the model
  model = Sequential()
  model.add(Dense(n_hidden, activation='relu', input_shape=(n_input,)))
  model.add(Dense(n_output))
# Compile the model
  model.compile(loss='mean_squared_error', optimizer='adam')
# build model using keras documentation recommended optimizer initialization
  optimizer = keras.optimizers.RMSprop(lr=0.001, rho=0.9, epsilon=1e-08, decay=0.0)
# run your model
  model.fit(X_train, y_train, epochs=1000, batch_size=50, verbose=0)
  return model



In [ ]:
MLP_1_trained= MLP_1(7,10,1,)

TypeError: ignored

In [ ]:
import pandas as pd
df= pd.read_csv("/content/df1_COMED_hourly.csv")

df.head()
df.shape
df.columns

Index(['date', 'load'], dtype='object')

In [ ]:
from numpy.core.fromnumeric import shape
df_1=df[0:2000]
df_1.shape

(2000, 2)

In [ ]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense

# Read in the time series data from CSV file
df = pd.read_csv('/content/df1_COMED_hourly.csv')
time_series = df['load'].values.astype('float64')

# Scale the data
scaler = MinMaxScaler()
time_series = scaler.fit_transform(time_series.reshape(-1, 1))

# Window the time series data
window_size = 7
horizon_size = 1
X, y = window_transform_series(time_series, window_size, horizon_size)

# Split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Define the model
model = Sequential()
model.add(Dense(10, activation='relu', input_shape=(window_size,)))
model.add(Dense(1))

# Compile the model
model.compile(loss='mean_squared_error', optimizer='adam')

# Train the model
model.fit(X_train, y_train, epochs=50, batch_size=32, verbose=1)


Epoch 1/50
1096/1096 [==============================] - 3s 2ms/step - loss: 0.0116
Epoch 2/50
1096/1096 [==============================] - 2s 2ms/step - loss: 0.0011
Epoch 3/50
1096/1096 [==============================] - 2s 2ms/step - loss: 8.3743e-04
Epoch 4/50
1096/1096 [==============================] - 2s 2ms/step - loss: 8.0434e-04
Epoch 5/50
1096/1096 [==============================] - 3s 2ms/step - loss: 7.8700e-04
Epoch 6/50
1096/1096 [==============================] - 2s 2ms/step - loss: 7.7826e-04
Epoch 7/50
1096/1096 [==============================] - 2s 1ms/step - loss: 7.6602e-04
Epoch 8/50
1096/1096 [==============================] - 2s 1ms/step - loss: 7.5852e-04
Epoch 9/50
1096/1096 [==============================] - 2s 2ms/step - loss: 7.5850e-04
Epoch 10/50
1096/1096 [==============================] - 2s 2ms/step - loss: 7.5223e-04
Epoch 11/50
1096/1096 [==============================] - 2s 2ms/step - loss: 7.4900e-04
Epoch 12/50
1096/1096 [==========================

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense

# Read in the time series data from CSV file
df = pd.read_csv('/content/df1_COMED_hourly.csv')
time_series = df['load'].values.astype('float64')

In [ ]:
# Scale the data
scaler = MinMaxScaler()
time_series = scaler.fit_transform(time_series.reshape(-1, 1))

# Window the time series data
window_size = 7
horizon_size = 1
X1, y1 = window_transform_series(df1, window_size, horizon_size)

print(X1.shape)

(35049, 7)


In [ ]:
print(y1.shape)

(35049,)


In [ ]:
print(np.squeeze(X1).shape)

(35049, 7)


In [ ]:
np.squeeze(np.array(y1))

array([0.39101474, 0.42644558, 0.46825397, ..., 0.36479592, 0.37110261,
       0.3768424 ])

In [ ]:
type(X_train)

list

In [ ]:
import numpy as np
np.squeeze(np.array(X_train)).shape

(35050, 7)

In [ ]:
print(np.array(X_train))

[[[0.41035998]
  [0.43728741]
  [0.45138889]
  ...
  [0.44820011]
  [0.42120181]
  [0.38669218]]

 [[0.21733277]
  [0.21095522]
  [0.23561508]
  ...
  [0.16354875]
  [0.12032313]
  [0.08659297]]

 [[0.24404762]
  [0.26374717]
  [0.27281746]
  ...
  [0.2769983 ]
  [0.2736678 ]
  [0.27324263]]

 ...

 [[0.10175737]
  [0.08354592]
  [0.07334184]
  ...
  [0.07454649]
  [0.08248299]
  [0.10508787]]

 [[0.22937925]
  [0.18594104]
  [0.17212302]
  ...
  [0.11954365]
  [0.10756803]
  [0.10728458]]

 [[0.17644558]
  [0.21570295]
  [0.26594388]
  ...
  [0.41135204]
  [0.46825397]
  [0.52685658]]]


In [ ]:
X, y = window_transform_series(time_series, window_size, horizon_size)
print(X[1])


[[0.16057256]
 [0.14703798]
 [0.15653345]
 [0.18905896]
 [0.2575822 ]
 [0.33241213]
 [0.39101474]]


In [ ]:
p

In [ ]:
print (y[1])

[[0.42644558]]


In [ ]:
print(X[2])

[[0.14703798]
 [0.15653345]
 [0.18905896]
 [0.2575822 ]
 [0.33241213]
 [0.39101474]
 [0.42644558]]


In [ ]:
print(y[2])

[[0.46825397]]


In [ ]:
type(X)

list

In [ ]:
print(len(X))

43813


In [ ]:
print(len(y))

43813


In [ ]:
print(len(X_train))

35050


In [ ]:
print(len(X_test))

8763


In [ ]:
print(len(y_train))

35050


In [ ]:
print(len(y_test))

8763


In [ ]:
train_test_split = 0.8*len(time_series) // 3   # set the split point

# partition the training set
X_train = X[:train_test_split]
y_train = y[:train_test_split]

# keep the last chunk for testing
X_test = X[train_test_split:]
y_test = y[train_test_split:]




In [ ]:
p1=int(0.8*len(time_series))

df1=time_series[:p1]
df2=time_series[p1:]

In [ ]:
print(len(df1))

35056


In [ ]:
print(len(df2))

8764


In [ ]:
print(len(time_series))

43820


In [ ]:
! pip install yfinance

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.9/55.9 KB 3.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 128.2/128.2 KB 9.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 112.2/112.2 KB 12.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 111.0/111.0 KB 14.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 62.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 KB 8.9 MB/s eta 0:00:00
  Attempting uninstall: requests
    Found existing installation: requests 2.25.1
    Uninstalling requests-2.25.1:
      Successfully uninstalled requests-2.25.1
  Attempting uninstall: html5lib
    Found existing installation: html5lib 1.0.1
    Uninstalling html5lib-1.0.1:
      Successfully uninstalled html5lib-1.0.1
  Attempting uninstall: beautifulsoup4
    Found existing installation: beautifulsoup4 4.6.3
   

In [ ]:
import yfinance as yf

In [ ]:
yf.to_csv("APPL")

AttributeError: ignored